name: Build ESP32 Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ESP-IDF
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev python3-setuptools
        pip3 install --upgrade pip
        pip3 install esp-idf

    - name: Install dependencies
      run: |
        cd firmware-espressif-esp32
        ./install.sh

    - name: Build the project
      run: |
        cd firmware-espressif-esp32
        idf.py build

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      with:
        files: firmware-espressif-esp32/build/firmware.bin
